name: Integrations
on:
  push:
    branches:
      - master

jobs:
  coveralls:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: [ '8.1' ]

    name: Code Coverage
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-progress

      - name: Generate clover.xml
        run: vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

      - name: Upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
